################  Function Introduction of the Playbook  ######################
###:      yum repo installation  
###:      yum install zabbix-agent zabbix-sender sysstat (iptables-services)
###:      mkdir /etc/zabbix/scripts 
###:      chmod 755, chown zabbix.zabbix
###:      generate .conf   using template
###:      add rules into iptables allow port 10050
###:      SELinux open these two ports (ignored this time)
###############################################################################

---
- hosts: testserver       #specify a group of hosts to apply the following tasks.
  remote_user: root
  gather_facts: yes    #gather the infomation of remote host

  vars:                 #self-defined variables
  - server_ip: "10.0.194.40"     ##### Zabbix Server IP Address#####

  tasks:
#  - name: "Install yum source repo of Zabbix 2.4(.8)!"    #For human reading
#    copy: src=zabbix.repo dest=/etc/yum.repos.d/ owner=root 

#  - name: "Install zabbix-agent using Yum!"
#    yum: name={{ item }} state=present
#    with_items:        #list the items to be installed in order
#    - zabbix-agent
#    - zabbix-sender
#    - sysstat
#    - iptables-services

  - name: "Create folder: /etc/zabbix/scripts!" #this folder is used for storingzabbix scripts
    file: path=/etc/zabbix/scripts owner=zabbix group=zabbix state=directory mode=755 

  - name: "Copy files (thread.py, top.py, processexist.sh) to the remote agents!"
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: zabbix
      mode: 0755
    with_items:
    - { src: "thread.sh", dest: "/etc/zabbix/scripts/thread.sh" }
    - { src: "top.sh", dest: "/etc/zabbix/scripts/top.sh" }
    - { src: "processexist.sh", dest: "/etc/zabbix/scripts/processexist.sh" }

 # - name: "Generate the configure file: /etc/zabbix/zabbix_agentd.conf"
 #   template: src=zabbixcnf.j2 dest=/etc/zabbix/zabbix_agentd.conf
 #   notify:       #call 'handler' when needed
 #   - restart zabbix-agent  # 'name' in 'handler'

 # - name: "Ensure zabbix-agent is running and enabled!"
 #   service: name=zabbix-agent state=started enabled=yes
 #
